IMAGE_CLASSIFIER_VERSION = 1.0.0
IMAGE_CLASSIFIER_SITE = $(BR2_EXTERNAL_EXTPACK_PATH)/package/image-classifier/src
IMAGE_CLASSIFIER_SITE_METHOD = local

IMAGE_CLASSIFIER_DEPENDENCIES = tensorflow-lite

IMAGE_CLASSIFIER_CONF_OPTS += \
    -DBR2_EXTERNAL_EXTPACK_PATH=$(BR2_EXTERNAL_EXTPACK_PATH) \
    -DD=$(@D)
    
$(eval $(cmake-package))
